## problema 18


In [1]:
import control as ctrl
import numpy as np

In [2]:
A=np.matrix([[-25,0,-.5],[0,0,1],[46.296,0,0]])
B=np.matrix([[5],[0],[0]])
C=np.matrix([0,.02,0])
D=np.matrix(0)

In [3]:
dc_motor= ctrl.ss(A,B,C,D)
dc_motor

A = [[-25.      0.     -0.5  ]
 [  0.      0.      1.   ]
 [ 46.296   0.      0.   ]]

B = [[5.]
 [0.]
 [0.]]

C = [[0.   0.02 0.  ]]

D = [[0.]]

In [5]:
plc1 = [-1-1j,-1+1j,-10]
print(np.linalg.eigvals(A))
dc_motor.zero()

[  0.         -24.03698401  -0.96301599]


array([], dtype=float64)

In [28]:
Co=ctrl.ctrb(A,B)
print('rango: ',np.linalg.matrix_rank(Co),'determinante: ',np.linalg.det(Co))

rango:  3 determinante:  -267914.9519999998


In [32]:
K=ctrl.acker(A,B,plc1)
K

matrix([[-2.6       ,  0.08640055, -0.00495939]])

In [33]:
np.linalg.eigvals(A-B@K)

array([-10.+0.j,  -1.+1.j,  -1.-1.j])

In [35]:
pe=[-4,-5+2j,-5-2j]
pe

[-4, (-5+2j), (-5-2j)]

In [37]:
Ob=ctrl.obsv(A,C)
print('rango: ',np.linalg.matrix_rank(Ob),'determinante: ',np.linalg.det(Ob))

rango:  3 determinante:  0.00037036799999999993


In [39]:
L=ctrl.acker(A.T,C.T,pe).T
L

matrix([[-8262.77864178],
        [ -550.        ],
        [16042.6       ]])

In [40]:
np.linalg.eigvals(A-L@C)

array([-5.+2.j, -5.-2.j, -4.+0.j])

### Punto c)

In [41]:
pe_r=[-5+2j,-5-2j]
pe_r

[(-5+2j), (-5-2j)]

In [46]:
T=np.matrix([[0,1,0],[50,0,0],[0,0,1]])

In [50]:
At=np.linalg.inv(T)@A@T
Bt=np.linalg.inv(T)@B
Ct= C@T
Dt=D
dc_motor_2=ctrl.ss(At,Bt,Ct,Dt)


In [53]:
n=At.shape[0]
Aaa=At[0,0]
Aab=At[0,1:n]
Aba=At[1:n,0]
Abb=At[1:n,1:n]

Ba=Bt[0,0]
Bb=Bt[1:n,0]

Ka=K[0,0]
Kb=K[0,1:n]

Lr=ctrl.acker(Abb.T,Aab.T,pe_r).T

Ar=Abb-Lr*Aab-(Bb-Lr*Ba)*Kb
Br=Ar*Lr+Aba-Lr*Aaa-(Bb-Lr*Ba)*Ka
Cr=-Kb
Dr=-Ka-Kb*Lr


In [54]:
Lr


matrix([[ 411.32279247],
        [-750.        ]])