In [1]:
## problema 2

In [2]:
import control as ctrl
import numpy as np


In [6]:
G1=ctrl.tf(1,[1,4])
G2=ctrl.tf(1,[2,0])
H1=ctrl.tf(1,[1,0])
H2=H1

In [12]:
 G=(((G2+H1*G2+1)*G1)/(1+G1*H2+G1*H1*H2*G2)).minreal()

In [13]:
G


        s^3 + 0.5 s^2 + 0.5 s
------------------------------------
s^4 + 4 s^3 + s^2 + 3.83e-14 s + 0.5

In [14]:
G.pole()

array([-3.721598  +0.j        , -0.65093674+0.j        ,
        0.18626737+0.41436783j,  0.18626737-0.41436783j])

In [15]:
G.zero()

array([-0.25+0.66143783j, -0.25-0.66143783j,  0.  +0.j        ])

In [17]:
sys=ctrl.ss(G)
sys

A = [[-4.00000000e+00 -1.00000000e+00 -3.83026943e-14 -5.00000000e-01]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]]

B = [[1.]
 [0.]
 [0.]
 [0.]]

C = [[1.  0.5 0.5 0. ]]

D = [[0.]]

In [18]:
np.linalg.eigvals(sys.A)

array([-3.721598  +0.j        , -0.65093674+0.j        ,
        0.18626737+0.41436783j,  0.18626737-0.41436783j])

In [19]:
G.pole()

array([-3.721598  +0.j        , -0.65093674+0.j        ,
        0.18626737+0.41436783j,  0.18626737-0.41436783j])