## problema 1

In [31]:
import numpy as np
import control as ctrl

In [33]:
A=np.matrix([[-2,1],[-2,0]])
B=np.matrix([[1],[3]])
C=np.matrix([1,0])
D=np.matrix(0)

In [36]:
ss=ctrl.ss(A,B,C,D)
ss

A = [[-2.  1.]
 [-2.  0.]]

B = [[1.]
 [3.]]

C = [[1. 0.]]

D = [[0.]]

In [40]:
ss_c , T= ctrl.canonical_form(ss,'reachable')
T

matrix([[-0.8,  0.6],
        [ 0.6, -0.2]])

In [41]:
ss_c.pole()

array([-1.+1.j, -1.-1.j])

In [42]:
ss.pole()

array([-1.+1.j, -1.-1.j])

In [45]:
ss_c.zero()

array([-3.+0.j])

In [46]:
ss.zero()

array([-3.+0.j])